### ISSUE TITLE
Docker Sickrage with NAS

### ISSUE THREAD

**Issue by luis4ndre** [linuxserver/docker-sickrage#16]
Hi,
I would to know if is possible use a NAS with this container?
If yes, how?

Thanks.

**Comment by j0nnymoe** [comment]
Hi,
If it supports docker, then yes.
In terms of how, it is all dependant on your NAS hardware.

**Comment by CHBMB** [comment]
@luis4ndre Might be helpful rather than just keep asking if a container actually works with a NAS if you tell us the specs of your NAS.  Otherwise you're not really giving us anything to go on whatsoever.

**Comment by luis4ndre** [comment]
Sorry,
I didn't express myself very well, I'm running a Docker in a PC (Linux or Windows), but I can't access a network folder inside a container.
I use a NAS only for storage.

Thanks.

**Comment by aptalca** [comment]
You can mount the network folders on your host, then you can map those folders in docker create command
