### ISSUE TITLE
python: can't open file '/app/sickrage/SickBeard.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by yoyos** [linuxserver/docker-sickrage#21]
> Cloning into '/app/sickrage'...
> fatal: could not read Username for 'https://github.com': No such device or address
> [cont-init.d] 30-install: exited 0.
> [cont-init.d] done.
> [services.d] starting services
> [services.d] done.
> python: can't open file '/app/sickrage/SickBeard.py': [Errno 2] No such file or directory
> python: can't open file '/app/sickrage/SickBeard.py': [Errno 2] No such file or directory
> python: can't open file '/app/sickrage/SickBeard.py': [Errno 2] No such file or directory
> python: can't open file '/app/sickrage/SickBeard.py': [Errno 2] No such file or directory
> ...(infinity)...

	
Didn't change a thing, juste pulled last linuxserver/sickrage docker image and rebuilt.
Even rebooted my box.

Am I alone with this ?

**Comment by yoyos** [comment]
Found why .. 🗡 

https://github.com/SickRage/SickRage
https://www.reddit.com/r/sickrage/comments/6oep02/false_dmca_request_has_taken_our_repos_down/

Temp fix:
https://www.reddit.com/r/sickrage/comments/6p676l/temporarty_dmcafix_for_you_running_sickrage_in_a/

**Comment by sparklyballs** [comment]
we're already aware of this and we're awaiting the outcome of the DMCA counterclaim filed by the github repos affected
