### ISSUE TITLE
nodejs missing when torrentz is enabled

### ISSUE THREAD

**Issue by rguichard** [linuxserver/docker-sickrage#29]
When torrentz is enable, nodejs is required as mentionned in https://github.com/Anorov/cloudflare-scrape#dependencies

```
11:39:00 ERROR::SEARCHQUEUE-BACKLOG-327417 :: [Torrentz] :: [5bc5c3a] Request failed: Missing Node.js runtime. Node is required. Please read the cfscrape README's Dependencies section: https://github.com/Anorov/cloudflare-scrape#dependencies.
Traceback (most recent call last):
  File "/app/sickrage/sickbeard/helpers.py", line 1525, in handle_requests_exception
    raise requests_exception
EnvironmentError: Missing Node.js runtime. Node is required. Please read the cfscrape README's Dependencies section: https://github.com/Anorov/cloudflare-scrape#dependencies
```

Is it feasible to add `nodejs` in the Docker base image or in the Dockerfile ? I don't know if this "issue" should be post here or on the base image git repo. Feel free to close it if I thought wrong.

**Comment by sparklyballs** [comment]
at the moment we are somewhat unclear as to whether sickrage are fixing this since that dependency has been there for cfscrape for a long time and it's only since a specific sickrage commit that the problem has arisen

**Comment by rguichard** [comment]
OK. For now, I rebuild a new Docker image based on linuxserver's one with nodejs.
Hope Sickrage will fix this someday...
