### ISSUE TITLE
Cannot use NZBtomedia

### ISSUE THREAD

**Issue by zaggash** [linuxserver/docker-sickrage#3]
Hello.

Nzbtomedia is included as a submodule in the contrib folder of sickrage.
It have to be available to the torrent client.
It could be fine to pull it and then expose it in the Dockerfile in the VOLUME statement.

**Comment by russell** [comment]
I solved this by mounting a copy of nzbtomedia into each container that needed it.  In the cases where there was no python installed, I'm installing that with a custom `userscript.sh` at container start.

To get the userscript to work you also need to create the container with the env ADVANCED_SCRIPT having some value.

**Comment by sparklyballs** [comment]
will be looking at developing a separate container for postprocessing, rather than bloat individual containers with dependencies required.
