### ISSUE TITLE
File access issue on /config dir

### ISSUE THREAD

**Issue by Xilhion** [linuxserver/docker-sickrage#31]
Hi, i don't recall since when i have the issue because i don't use it often, however, here is my problem:
If sickrage start with user 'abc', it says "Datadir must be writable: /config". But the /config dir IS writable and owned by abc:abc. I ran chown and chmod 777 as troubleshooting step
```
root@f5c0982f3d14:/$ ls -la /config
total 4148
drwxrwxrwx 5 abc  abc     4096 May  4 11:57 .
drwxr-xr-x 1 root root    4096 Apr 30 12:14 ..
drwxrwxrwx 2 abc  abc     4096 Apr 30 12:06 Logs
drwxrwxrwx 2 abc  abc     4096 Apr 30 12:06 backup
drwxrwxrwx 4 abc  abc     4096 May  4 11:59 cache
-rwxrwxrwx 1 abc  abc   708608 May  4 11:40 cache.db
-rwxrwxrwx 1 abc  abc    25246 May  4 11:59 config.ini
-rwxrwxrwx 1 abc  abc    16384 Sep  2  2017 failed.db
-rwxrwxrwx 1 abc  abc  3391488 May  4 11:57 sickbeard.db
-rwxrwxrwx 1 abc  abc    81920 Sep  2  2017 sickbeard.db.v43
```

Now, when i run it under the root user using the following command, it runs fine : 
```
root@f5c0982f3d14:/$ s6-setuidgid root python /app/sickrage/SickBeard.py --datadir /config
```

Strange behaviour is that if i access the /config dir in command line as user abc within the container, i do have full access on it (i can modify, create and delete files). I tried setting the GUID/PGID through the docker create command but it does change the id but still same issue.
I tried to recreate everything from scratch (backup the config folder elsewhere and create a new one) but the issue keep occuring.

The folder is hosted on a Synology share folder with NFS mount and NFS access as read/write for the IP of the docker host.
I have other containers runing on the same host, accessing other subfolder on the same share and they are working fine (Radarr, 

Docker host is VMWare Photon OS 2.0 on a VMware 6.5 esxi.
Here is the create command : 
```
 docker create --name sickrage --restart=unless-stopped -v /mnt/config/sickrage:/config -v /mnt/downloads:/downloads -v /mnt/series:/tv -e TZ=Europe/Brussels -p 8081:8081 -e PGID=1001 -e PUID=1001 linuxserver/sickrage
```

And the mount NFS command : 
```
<synology IP>:/volume1/dockerspace/tmpDownload    /mnt/downloads   nfs auto,nofail,noatime,nolock,intr,tcp,actimeo=1800 0 0
<synology IP>:/volume1/dockerspace/config    /mnt/config   nfs auto,nofail,noatime,nolock,intr,tcp,actimeo=1800 0 0
<synology IP>:/volume1/Series    /mnt/series   nfs auto,nofail,noatime,nolock,intr,tcp,actimeo=1800 0 0
```

And the logs : 
```
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donations/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1001
User gid:    1001
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```
Error log:
```
usermod: no changes
Data directory must be writeable: /config
Data directory must be writeable: /config
Data directory must be writeable: /config
Data directory must be writeable: /config
...
```

I have now used all my linux/docker knowledge to troubleshoot and still stuck on this issue.

Thanks for your help

**Comment by j0nnymoe** [comment]
It will be due to using a NFS mount as your /config folder. Change it to your local FS and see if the issue occurs.

**Comment by Xilhion** [comment]
I'll try when i get back home this evening.
However, it was working perfectly fine until this issue arise (shame on me for not remembering when and what changed)
And it is working fine with other container on the same host using the same /mnt/config mount (e.g. linuxserver/radarr is working flawlessly)

And i'd rather have it working without having the config dir local to the docker host.

**Comment by j0nnymoe** [comment]
We generally don't support having the `/config` folders on NFS mounts as we've seen issues with different applications, so it's at your own risk. 

Let us know how you get on with testing on the local file system - atleast we'll be able to confirm if it's the image or the nfs mount.

**Comment by Xilhion** [comment]
So i finally did the test: 
- Copied everything from my mounted folder to a local folder
- fixed ownership and perms same as in the mounted folder
- re-created the container with the new volume mapping 

And it works. So indeed the issue is related to the NFS. 
I'll investigate this on my own then. I may have change something there.

Thanks
