### ISSUE TITLE
SickRage does not move files instantly when postprocessing

### ISSUE THREAD

**Issue by theincredibleman** [linuxserver/docker-sickrage#34]
Openmediavault 4.0  

Config:

<img width="637" alt="screen shot 2018-08-29 at 18 21 11" src="https://user-images.githubusercontent.com/42136559/44801073-5f89d200-abb8-11e8-9d20-16defcf8497a.png">

For some reason SickRage is not moving the files when postprocessing (move has been set as method), but it is doing what seems like a network copy.
I can see the files slowly growing at the destination folder instead of being instantly moved.

All folders are on the same disk, although they are different shared folders.

**Comment by sparklyballs** [comment]
docker doesn't know that 2 different volume mounts are on the same disk on the host and will therefore perform copy write as linux does automatically when moving data between disks

**Comment by theincredibleman** [comment]
Thank you for your answer. So there is no way to prevent this? Would hard/soft linking be a better option?
