### ISSUE TITLE
Wrong sickrage repo

### ISSUE THREAD

**Issue by OmgImAlexis** [linuxserver/docker-sickrage#35]
The sickrage repo needs to be updated to use the new `Sick-Rage/Sick-Rage` repo as per https://github.com/Sick-Rage/Sick-Rage/issues/4984.

**Comment by OmgImAlexis** [comment]
@sparklyballs this should be fixed as soon as possible otherwise users will end up on the illegitimate version with a broken database.

**Comment by TiagoDM** [comment]
tried to change on .git folder (windows install) config and fetch_head files to "sick-rage" repo, but when i restart sick-rage, the files are "restored" to "sickrage" again...

**Comment by TiagoDM** [comment]
Managed to make sickrage (or sick-rage now) to fetch from sick-rage.git by modifying those files (post above) and %systemdrive%/sickrage/data/config.ini. I only had to replace "sickrage" with "sick-rage".

**Comment by alex-phillips** [comment]
This should be fixed in the latest image now.

**Comment by CHBMB** [comment]
We've update the `armhf` and `arm64`images too....

**Comment by OmgImAlexis** [comment]
Thank you so much. ❤️
