### ISSUE TITLE
Sick rage is attempting to access a URL on boot that doesn't exist

### ISSUE THREAD

**Issue by Walms** [linuxserver/docker-sickrage#41]
When running up the image the following error is shows 

WARNING::MAIN :: Updating network timezones failed, this can happen from time to time. URL: http://sick-rage.github.io/sb_network_timezones/network_timezones.txt

Ubuntu 18.04

 docker create --name=sickrage -v /home/dan/sickrage/confi:/config -v /home/dan/sickrage/downloads:/downloads -v /home/dan/plex/instance1/media:/tv -e TZ=Pacific/Auckland -p 8081:8081 linuxserver/sickrage

21:36:26 INFO::DAILYSEARCHER :: Request failed: 404 Client Error: Not Found for url: http://sick-rage.github.io/sb_network_timezones/network_timezones.txt
21:36:26 WARNING::DAILYSEARCHER :: Updating network timezones failed, this can happen from time to time. URL: http://sick-rage.github.io/sb_network_timezones/network_timezones.txt

No symlinks

**Comment by tobbenb** [comment]
That is not something to do with us. If you check github yourself, you can see that there is sick-rage anymore. Check the other issue on this repo.
